name: WebhookReport

version: '1.0-SNAPSHOT'

main: com.ooqe.WebhookReport.Main

api-version: '1.21'

commands:

  report:

    description: Reports a player to the staff team

    usage: /<command>

    aliases: [skibidilmao]
